# Generated by Django 5.0.1 on 2024-01-21 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('token_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('symbol', models.CharField(max_length=255)),
                ('logo', models.URLField(max_length=1000)),
                ('coinmarketcap_url', models.URLField(max_length=1000)),
                ('circulating_supply', models.PositiveBigIntegerField()),
                ('total_supply', models.PositiveBigIntegerField(null=True)),
                ('max_supply', models.PositiveBigIntegerField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.platform')),
                ('tags', models.ManyToManyField(to='currency.tag')),
                ('urls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.url')),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
