# Generated by Django 5.0.1 on 2024-01-22 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('symbol', models.CharField(max_length=255)),
                ('logo', models.URLField(max_length=1000)),
                ('coinmarketcap_url', models.URLField(max_length=1000)),
                ('circulating_supply', models.PositiveBigIntegerField(null=True)),
                ('total_supply', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
                ('max_supply', models.PositiveBigIntegerField(null=True)),
                ('platform', models.CharField(max_length=255, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(to='currency.tag')),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
