# Generated by Django 5.0.1 on 2024-01-21 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='urls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.url'),
        ),
    ]
