# Generated by Django 5.0.1 on 2024-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('market_id', models.IntegerField(primary_key=True, serialize=False)),
                ('market_pair', models.CharField(max_length=255)),
                ('market_reputation', models.IntegerField()),
                ('market_score', models.CharField(max_length=255)),
                ('market_url', models.CharField(max_length=255)),
                ('base_currency_id', models.IntegerField()),
                ('base_symbol', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('center_type', models.CharField(max_length=255)),
                ('depth_usd_negative_two', models.DecimalField(decimal_places=15, max_digits=25)),
                ('depth_usd_positive_two', models.DecimalField(decimal_places=15, max_digits=25)),
                ('effective_liquidity', models.DecimalField(decimal_places=15, max_digits=25)),
                ('exchange_id', models.IntegerField()),
                ('exchange_name', models.CharField(max_length=255)),
                ('exchange_notice', models.CharField(max_length=255)),
                ('exchange_slug', models.CharField(max_length=255)),
                ('fee_type', models.CharField(max_length=255)),
                ('index_price', models.IntegerField()),
                ('is_verified', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('outlier_detected', models.IntegerField()),
                ('por_audit_status', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=15, max_digits=25)),
                ('price_excluded', models.IntegerField()),
                ('quote', models.DecimalField(decimal_places=15, max_digits=25)),
                ('quote_currency_id', models.IntegerField()),
                ('quote_symbol', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('reserves_available', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('volume_base', models.DecimalField(decimal_places=15, max_digits=25)),
                ('volume_excluded', models.IntegerField()),
                ('volume_percent', models.DecimalField(decimal_places=15, max_digits=25)),
                ('volume_quote', models.DecimalField(decimal_places=15, max_digits=25)),
                ('volume_usd', models.DecimalField(decimal_places=15, max_digits=25)),
                ('platform_id', models.IntegerField(null=True)),
                ('platform_name', models.CharField(max_length=255, null=True)),
                ('pair_contract_address', models.CharField(max_length=255, null=True)),
                ('liquidity', models.DecimalField(decimal_places=15, max_digits=25, null=True)),
                ('dexer_url', models.URLField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='currency',
            name='pairs',
            field=models.ManyToManyField(to='currency.pair'),
        ),
    ]
