# Generated by Django 5.0.1 on 2024-01-21 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_currency_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='token_address',
        ),
    ]
