# Generated by Django 5.0.1 on 2024-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_remove_platform_token_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='max_supply',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
