# Generated by Django 5.0.1 on 2024-01-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_pair_effective_liquidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
