# Generated by Django 5.0.1 on 2024-01-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_currency_max_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='total_supply',
            field=models.BigIntegerField(null=True),
        ),
    ]
