# Generated by Django 5.0.1 on 2024-01-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_remove_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='href',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
