# Generated by Django 5.0.1 on 2024-01-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_currency_total_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='total_supply',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
    ]
