# Generated by Django 5.0.1 on 2024-01-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_currency_total_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.platform'),
        ),
    ]
