# Generated by Django 5.0.1 on 2024-01-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_pair_options_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='time',
            field=models.IntegerField(),
        ),
    ]
