# Generated by Django 5.0.1 on 2024-01-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_alter_value_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='time',
            field=models.BigIntegerField(),
        ),
    ]
