# Generated by Django 5.0.1 on 2024-02-02 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_alter_value_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 2, 13, 41, 1, 394864, tzinfo=datetime.timezone.utc)),
        ),
    ]
